/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testlogin;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ibnibrahim
 */
public class Produit extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    Connection myconObj = null;
    Statement mystatObj = null;
    ResultSet myresObj = null;
    public Produit() {
        initComponents();
        setSize(820, 350);
        setResizable(false);
        setLocationRelativeTo(null);
        if (TxtFieldIdProd.getText().isEmpty() == false) {
            BtnAjoutProd.setEnabled(false);
        }
        selectionall();
    }   
    
    public void selectionall(){
        try {
            myconObj = DriverManager.getConnection("jdbc:mysql://localhost:3306/Gestion_Pharmacie", "root", "");
            mystatObj = myconObj.createStatement();
            myresObj = mystatObj.executeQuery("SELECT * FROM Produit");
            Produit.setModel(DbUtils.resultSetToTableModel(myresObj));
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void ajout() {
        try {
            PreparedStatement st = myconObj.prepareStatement("INSERT INTO Produit VALUES (?, ?, ?, ?)");
            st.setString(1, TxtFieldIdProd.getText());
            st.setString(2, TxtFieldNomProd.getText());
            st.setString(3, TxtFieldPrixProd.getText());
            st.setString(4, TxtFieldTypeProd.getText());
            st.executeUpdate();
            TxtFieldIdProd.setText("");
            TxtFieldNomProd.setText("");
            TxtFieldPrixProd.setText("");
            TxtFieldTypeProd.setText("");
        }
        catch (SQLException E) {
            E.printStackTrace();
        }
        selectionall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Produit = new javax.swing.JTable();
        BtnAjoutProd = new javax.swing.JButton();
        BtnMiseAJourProd = new javax.swing.JButton();
        BtnSuprProd = new javax.swing.JButton();
        TxtFieldIdProd = new javax.swing.JTextField();
        TxtFieldNomProd = new javax.swing.JTextField();
        TxtFieldPrixProd = new javax.swing.JTextField();
        TxtFieldTypeProd = new javax.swing.JTextField();
        LabIdProd = new javax.swing.JLabel();
        LabNomProd = new javax.swing.JLabel();
        LabPrixProd = new javax.swing.JLabel();
        LabTypeProd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(100, 225, 137));

        jPanel1.setBackground(new java.awt.Color(100, 225, 137));

        Produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idProd", "nom", "prix", "type"
            }
        ));
        jScrollPane1.setViewportView(Produit);

        BtnAjoutProd.setText("Ajouter");
        BtnAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutProdActionPerformed(evt);
            }
        });

        BtnMiseAJourProd.setText("Mettre à jour");
        BtnMiseAJourProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMiseAJourProdActionPerformed(evt);
            }
        });

        BtnSuprProd.setText("Supprimer");
        BtnSuprProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuprProdActionPerformed(evt);
            }
        });

        TxtFieldIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdProdActionPerformed(evt);
            }
        });

        LabIdProd.setText("ID");

        LabNomProd.setText("Nom");

        LabPrixProd.setText("Prix");

        LabTypeProd.setText("Type");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testlogin/retour-accueil-vert-logo-1.jpg")));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(LabNomProd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(BtnSuprProd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(BtnMiseAJourProd)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabPrixProd)
                                .addGap(19, 19, 19))
                            .addComponent(LabTypeProd)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabIdProd)
                        .addGap(17, 17, 17)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtFieldIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFieldPrixProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFieldTypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFieldNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabIdProd))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFieldPrixProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabPrixProd))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldTypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabTypeProd))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAjoutProd)
                            .addComponent(BtnSuprProd)
                            .addComponent(BtnMiseAJourProd))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMiseAJourProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMiseAJourProdActionPerformed
        // TODO add your handling code here:
        
        try {
            PreparedStatement st = myconObj.prepareStatement("UPDATE Produit SET nom=?, prix=?, type=? WHERE idProd=?");
            st.setString(1, TxtFieldNomProd.getText());
            st.setString(2, TxtFieldPrixProd.getText());
            st.setString(3, TxtFieldTypeProd.getText());
            st.setString(4, TxtFieldIdProd.getText());
            st.executeUpdate();
            TxtFieldIdProd.setText("");
            TxtFieldNomProd.setText("");
            TxtFieldPrixProd.setText("");
            TxtFieldTypeProd.setText("");
        }
        catch (SQLException E) {
            E.printStackTrace();
        }
        selectionall();
    }//GEN-LAST:event_BtnMiseAJourProdActionPerformed

    private void TxtFieldIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdProdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtFieldIdProdActionPerformed

    private void BtnSuprProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuprProdActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement st = myconObj.prepareStatement("DELETE FROM Produit WHERE idProd=? OR nom=? OR prix=? OR type=?");
            st.setString(1, TxtFieldIdProd.getText());
            st.setString(2, TxtFieldNomProd.getText());
            st.setString(3, TxtFieldPrixProd.getText());
            st.setString(4, TxtFieldTypeProd.getText());
            st.executeUpdate();
            TxtFieldIdProd.setText("");
            TxtFieldNomProd.setText("");
            TxtFieldPrixProd.setText("");
            TxtFieldTypeProd.setText("");
        }
        catch (SQLException E) {
            E.printStackTrace();
        }
        selectionall();
    }//GEN-LAST:event_BtnSuprProdActionPerformed

    
    
    private void BtnAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutProdActionPerformed
        // TODO add your handling code here:
        if (TxtFieldNomProd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        } else {
            ajout();
            
        }
        
    }//GEN-LAST:event_BtnAjoutProdActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pharmacie g=new pharmacie();
        setVisible(false);
        g.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjoutProd;
    private javax.swing.JButton BtnMiseAJourProd;
    private javax.swing.JButton BtnSuprProd;
    private javax.swing.JLabel LabIdProd;
    private javax.swing.JLabel LabNomProd;
    private javax.swing.JLabel LabPrixProd;
    private javax.swing.JLabel LabTypeProd;
    private javax.swing.JTable Produit;
    private javax.swing.JTextField TxtFieldIdProd;
    private javax.swing.JTextField TxtFieldNomProd;
    private javax.swing.JTextField TxtFieldPrixProd;
    private javax.swing.JTextField TxtFieldTypeProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
